# -*- coding: utf-8 -*-
"""A2_game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1En56ivmsrKJqS4c0MNl8jqhb3DaTbsVk
"""

print("Welcome to Number Sequence Game")

def check_sequence (number, piece_length):
  pieces = [int(str(number)[i:i+piece_length]) for i in range(0, len(str(number)), piece_length)] #So I first convert the number to string. Then the string will split into pieces
  return all(pieces[i] <= pieces[i+1] for i in range(len(pieces)-1)) #This code of line makes sure all the numbers are increasing and it will check if the number is less than or equal to the next one

def main():
  score = 0 #This is a variable that starts at 0 and increases each time the user finishes an order
  losing_score = 0 #This is a variable that also starts at 0 and increases each time the user does not finishes an order

  while score < 5 and losing_score < 5: #While loop to keep the player get a score of 5
        try:
            number = int(input("Enter a number: ")) #Ask the user to enter a number
            piece_length = int(input("Enter the number of digits in each piece: ")) #Ask the user to enter the number of digits for the piece length

            if check_sequence(number, piece_length): #This checks whether the number is increasing
                print("The pieces are in numerically increasing order.") #If it is, it will print and increase by 1
                score += 1
            else:
                print("The pieces are not in numerically increasing order.") #Otherwise, the score will print 0
                score = 0

            losing_score += 1 if not check_sequence(number, piece_length) else 0 #If the piece is not increasing order, it will increase the losing score by 1, if not it won't change anything

        except ValueError: #If the user enters the right string but wrong value
            print("Invalid input. Please enter a whole number.") #It will print an error

  if score >= 5: #If the score is greater than or equal to 5
        print("Congratulations! You won!") #It prints congratulations
  elif losing_score >= 5: #Otherwise
        print("You lost!") #It will print You lost

if __name__ == "__main__": #This function checks if this is run as the main program
    main()